[Interface]
PrivateKey = ${LATVIA_AWG_PRIVATE_KEY}
Address = 10.10.0.2/24
ListenPort = 51820

Jc = ${AWG_JC}
Jmin = ${AWG_JMIN}
Jmax = ${AWG_JMAX}
S1 = ${AWG_S1}
S2 = ${AWG_S2}
H1 = ${AWG_H1}
H2 = ${AWG_H2}
H3 = ${AWG_H3}
H4 = ${AWG_H4}

PostUp = iptables -t nat -A POSTROUTING -o $(ip route show default | awk '{print $5}') -j MASQUERADE
PostUp = ip6tables -t nat -A POSTROUTING -o $(ip route show default | awk '{print $5}') -j MASQUERADE
PostDown = iptables -t nat -D POSTROUTING -o $(ip route show default | awk '{print $5}') -j MASQUERADE
PostDown = ip6tables -t nat -D POSTROUTING -o $(ip route show default | awk '{print $5}') -j MASQUERADE

[Peer]
PublicKey = ${RUSSIA_AWG_PUBLIC_KEY}
PresharedKey = ${AWG_PRESHARED_KEY}
AllowedIPs = 10.10.0.1/32
