[Interface]
# Finland WireGuard Server
PrivateKey = ${FINLAND_WG_PRIVATE_KEY}
Address = 10.10.0.2/24
ListenPort = 51820

PostUp = iptables -t nat -A POSTROUTING -o $(ip route show default | awk '{print $5}') -j MASQUERADE
PostUp = ip6tables -t nat -A POSTROUTING -o $(ip route show default | awk '{print $5}') -j MASQUERADE
PostDown = iptables -t nat -D POSTROUTING -o $(ip route show default | awk '{print $5}') -j MASQUERADE
PostDown = ip6tables -t nat -D POSTROUTING -o $(ip route show default | awk '{print $5}') -j MASQUERADE

[Peer]
# Russia Server
PublicKey = ${RUSSIA_WG_PUBLIC_KEY}
PresharedKey = ${WG_PRESHARED_KEY}
AllowedIPs = 10.10.0.1/32
