[Interface]
PrivateKey = ${RUSSIA_AWG_PRIVATE_KEY}
Address = 10.10.0.1/24
Table = off

Jc = ${AWG_JC}
Jmin = ${AWG_JMIN}
Jmax = ${AWG_JMAX}
S1 = ${AWG_S1}
S2 = ${AWG_S2}
H1 = ${AWG_H1}
H2 = ${AWG_H2}
H3 = ${AWG_H3}
H4 = ${AWG_H4}

PostUp = ip rule add fwmark 1 table 100
PostUp = ip route add default dev awg0 table 100
PostDown = ip rule del fwmark 1 table 100
PostDown = ip route del default dev awg0 table 100

[Peer]
PublicKey = ${LATVIA_AWG_PUBLIC_KEY}
PresharedKey = ${AWG_PRESHARED_KEY}
Endpoint = ${LATVIA_IP}:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
